/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inlämningsprojekt_ny;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author svanteskold
 */
public class AdminHallbarhetsmal extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    private int aid;

    /**
     * Creates new form Hallbarhetsmal
     */
    public AdminHallbarhetsmal(InfDB idb, String inloggadAnvandare, int aid) {
        this.idb=idb;
        this.inloggadAnvandare=inloggadAnvandare;
        this.aid = aid;
        initComponents();
        hamtaHallbarhetsmal();
        hallbarhetsmalText.setEditable(false);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        hallbarhetsmalTillbakaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hallbarhetsmalText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hallbarhetsmalTillbakaButton.setText("Tillbaka");
        hallbarhetsmalTillbakaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallbarhetsmalTillbakaButtonActionPerformed(evt);
            }
        });

        hallbarhetsmalText.setColumns(20);
        hallbarhetsmalText.setRows(5);
        jScrollPane1.setViewportView(hallbarhetsmalText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(hallbarhetsmalTillbakaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hallbarhetsmalTillbakaButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hamtaHallbarhetsmal() {
    try {
        String sql = "SELECT * FROM hallbarhetsmal ORDER BY hid";
        var resultat = idb.fetchRows(sql);

        StringBuilder sb = new StringBuilder();

        for (var rad : resultat) {
            String id = rad.get("hid");
            String namn = rad.get("namn");
            String beskrivning = rad.get("beskrivning");
            String malnummer = rad.get("malnummer");
            String prioritet = rad.get("prioritet");

            sb.append("hid: ").append(id)
              .append(" | Mål ").append(malnummer)
              .append(": ").append(namn).append("\n")
              .append("Prioritet: ").append(prioritet).append("\n")
              .append(beskrivning).append("\n\n");
        }

        hallbarhetsmalText.setText(sb.toString()); 

    } catch (InfException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte hämta mål: " + e.getMessage());
    }
    }
    
    private void hallbarhetsmalTillbakaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallbarhetsmalTillbakaButtonActionPerformed
        // TODO add your handling code here:
        new AdminMeny(idb, inloggadAnvandare, aid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hallbarhetsmalTillbakaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHallbarhetsmal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHallbarhetsmal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHallbarhetsmal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHallbarhetsmal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //new Hallbarhetsmal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextArea hallbarhetsmalText;
    private javax.swing.JButton hallbarhetsmalTillbakaButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}