package inlämningsprojekt_ny;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import inlämningsprojekt_ny.Validering;
import java.awt.event.ActionEvent;
import oru.inf.InfDB;
/**
 *
 * @author joelj
 */
public class AdminHallbarhetavd extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;
    private int aid;

    /**
     * Creates new form Hallbarhetavd
     */
    public AdminHallbarhetavd(InfDB idb, String inloggadAnvandare, int aid) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.aid = aid;
        initComponents();
        jScrollPane1.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        HallbarhetavdTillbakaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hallbarhetPersonalField = new javax.swing.JTextArea();
        hallbarhetAvdPersonalButton = new javax.swing.JButton();
        hallbarhetAvdProjektButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hallbarhetAvdProjektField = new javax.swing.JTextArea();
        pAvdHallbarhetButton = new javax.swing.JToggleButton();
        aAvdHallbarhetButton = new javax.swing.JToggleButton();
        plaAvdHallbarhetButton = new javax.swing.JToggleButton();
        sokHandlaggarField = new javax.swing.JTextField();
        sokHandlaggareButton = new javax.swing.JButton();
        sokProjektField = new javax.swing.JTextField();
        sokProjektField2 = new javax.swing.JTextField();
        sokProjektLabel = new javax.swing.JLabel();
        sokProjektLabel2 = new javax.swing.JLabel();
        sokProjektDatumButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HallbarhetavdTillbakaButton.setText("Tillbaka");
        HallbarhetavdTillbakaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HallbarhetavdTillbakaButtonActionPerformed(evt);
            }
        });

        hallbarhetPersonalField.setColumns(20);
        hallbarhetPersonalField.setRows(5);
        jScrollPane1.setViewportView(hallbarhetPersonalField);

        hallbarhetAvdPersonalButton.setText("Personal Lista");
        hallbarhetAvdPersonalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallbarhetAvdPersonalButtonActionPerformed(evt);
            }
        });

        hallbarhetAvdProjektButton.setText("Projekt Lista");
        hallbarhetAvdProjektButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallbarhetAvdProjektButtonActionPerformed(evt);
            }
        });

        hallbarhetAvdProjektField.setColumns(20);
        hallbarhetAvdProjektField.setRows(5);
        jScrollPane2.setViewportView(hallbarhetAvdProjektField);

        buttonGroup1.add(pAvdHallbarhetButton);
        pAvdHallbarhetButton.setText("Pågående");
        pAvdHallbarhetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAvdHallbarhetButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(aAvdHallbarhetButton);
        aAvdHallbarhetButton.setText("Avslutande");
        aAvdHallbarhetButton.setBorderPainted(false);
        aAvdHallbarhetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAvdHallbarhetButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(plaAvdHallbarhetButton);
        plaAvdHallbarhetButton.setText("Planerat");
        plaAvdHallbarhetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plaAvdHallbarhetButtonActionPerformed(evt);
            }
        });

        sokHandlaggarField.setColumns(12);
        sokHandlaggarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokHandlaggarFieldActionPerformed(evt);
            }
        });

        sokHandlaggareButton.setBackground(new java.awt.Color(204, 204, 204));
        sokHandlaggareButton.setText("Sök Handläggare");
        sokHandlaggareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokHandlaggareButtonActionPerformed(evt);
            }
        });

        sokProjektField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokProjektFieldActionPerformed(evt);
            }
        });

        sokProjektField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokProjektField2ActionPerformed(evt);
            }
        });

        sokProjektLabel.setText("Från:");

        sokProjektLabel2.setText("Till:");

        sokProjektDatumButton.setText("Sök Projekt");
        sokProjektDatumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokProjektDatumButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sokHandlaggarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sokHandlaggareButton)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(sokProjektLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(sokProjektField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(sokProjektLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sokProjektField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(sokProjektDatumButton)
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HallbarhetavdTillbakaButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(plaAvdHallbarhetButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pAvdHallbarhetButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aAvdHallbarhetButton)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(hallbarhetAvdPersonalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hallbarhetAvdProjektButton)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HallbarhetavdTillbakaButton)
                    .addComponent(pAvdHallbarhetButton)
                    .addComponent(aAvdHallbarhetButton)
                    .addComponent(plaAvdHallbarhetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sokProjektField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sokProjektLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sokHandlaggarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sokHandlaggareButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sokProjektField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sokProjektLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sokProjektDatumButton)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hallbarhetAvdPersonalButton)
                    .addComponent(hallbarhetAvdProjektButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HallbarhetavdTillbakaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HallbarhetavdTillbakaButtonActionPerformed
        // TODO add your handling code here:
        new Avdelning(idb, inloggadAnvandare, aid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HallbarhetavdTillbakaButtonActionPerformed

    private void hallbarhetAvdPersonalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallbarhetAvdPersonalButtonActionPerformed
        // TODO add your handling code here:
        try {
    String sql = "SELECT fornamn, efternamn FROM anstalld " + 
                 "JOIN avdelning ON anstalld.avdelning = avdelning.avdid " + 
                 "WHERE avdelning.namn = 'Avdelning för Hållbar Energi och Klimatförändringar'";

    var resultat = idb.fetchRows(sql);

    if (resultat != null && !resultat.isEmpty()) {
        StringBuilder sb = new StringBuilder();
        for (var rad : resultat) {
            sb.append(rad.get("fornamn")).append(" ").append(rad.get("efternamn")).append("\n");
        }
        hallbarhetPersonalField.setText(sb.toString());
        jScrollPane1.setVisible(true);
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    } else {
        hallbarhetPersonalField.setText("Inga personer hittades.");
        jScrollPane1.setVisible(true);
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }
} catch (Exception e) {
    hallbarhetPersonalField.setText("Fel: " + e.getMessage());
    jScrollPane1.setVisible(true);
    jScrollPane1.revalidate();
    jScrollPane1.repaint();
}
        
    }//GEN-LAST:event_hallbarhetAvdPersonalButtonActionPerformed

    private void hallbarhetAvdProjektButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallbarhetAvdProjektButtonActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT DISTINCT p.projektnamn FROM projekt p " + 
                    "JOIN proj_hallbarhet ph ON p.pid = ph.pid " + 
                    "JOIN avd_hallbarhet ah ON ph.hid = ah.hid " + 
                    "JOIN avdelning a ON ah.avdid = a.avdid " +
                    "WHERE a.namn = 'Avdelning för Hållbar Energi och Klimatförändringar' ";
            
            var resultat = idb.fetchRows(sql);
            
            if (resultat != null && !resultat.isEmpty()) {
                StringBuilder sb = new StringBuilder();
                for (var rad : resultat) {
                    sb.append(rad.get("projektnamn")).append("\n");
                }
                hallbarhetAvdProjektField.setText(sb.toString());
                jScrollPane2.setVisible(true);
            } else {
                hallbarhetAvdProjektField.setText("Inga projekt hittades.");
                jScrollPane2.setVisible(true);
            }
      } catch (Exception e) {
          hallbarhetAvdProjektField.setText("Fel: " + e.getMessage());
          jScrollPane2.setVisible(true);
      }
    }//GEN-LAST:event_hallbarhetAvdProjektButtonActionPerformed

    private void pAvdHallbarhetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAvdHallbarhetButtonActionPerformed
        // TODO add your handling code here:
        String status = "Pågående";
        
        if(Validering.kollaStatus(status)){
            try{
                String sql ="SELECT DISTINCT p.projektnamn FROM projekt p " +
                        "JOIN proj_hallbarhet ph ON p.pid = ph.pid " +
                        "JOIN avd_hallbarhet ah ON ph.hid = ah.hid " +
                        "JOIN avdelning a ON ah.avdid = a.avdid " +
                        "WHERE a.namn = 'Avdelning för Hållbar Energi och Klimatförändringar' " +
                        "AND p.status = '" + status + "'";
                
               var resultat = idb.fetchRows(sql);
               StringBuilder sb = new StringBuilder();
               
               if(resultat != null && !resultat.isEmpty()){
                   for(var rad : resultat){
                       sb.append(rad.get("projektnamn")).append("\n");
                   }
                   hallbarhetAvdProjektField.setText(sb.toString());
               }else{
                   hallbarhetAvdProjektField.setText("Inga projekt med status '" + status + "'hittades.");
               }
            }catch (Exception e){
                hallbarhetAvdProjektField.setText("Fel: " + e.getMessage());
            }
        }else{
            hallbarhetAvdProjektField.setText("Ogiltig status:" + status);
        }
    }//GEN-LAST:event_pAvdHallbarhetButtonActionPerformed

    private void aAvdHallbarhetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAvdHallbarhetButtonActionPerformed
        // TODO add your handling code here:
        String status = "Avslutat";
        
        if(Validering.kollaStatus(status)){
            try{
                String sql = "SELECT DISTINCT p.projektnamn FROM projekt p " +
                        "JOIN proj_hallbarhet ph ON p.pid = ph.pid " +
                        "JOIN avd_hallbarhet ah ON ph.hid = ah.hid " +
                        "JOIN avdelning a ON ah.avdid = a.avdid " +
                        "WHERE a.namn = 'Avdelning för Hållbar Energi och Klimatförändringar' "+
                        "AND p.status = '" + status + "'";
                
               var resultat = idb.fetchRows(sql);
               StringBuilder sb = new StringBuilder();
               
               if(resultat != null && !resultat.isEmpty()){
                   for(var rad : resultat){
                       sb.append(rad.get("projektnamn")).append("\n");
                   }
                   hallbarhetAvdProjektField.setText(sb.toString());
               }else{
                   hallbarhetAvdProjektField.setText("Inga projekt med status '" + status + "'hittades.");
               }
            }catch (Exception e){
                hallbarhetAvdProjektField.setText("Fel: " + e.getMessage());
            }
        }else {
            hallbarhetAvdProjektField.setText("Ogiltig status: " + status);
        }
    }//GEN-LAST:event_aAvdHallbarhetButtonActionPerformed

    private void plaAvdHallbarhetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plaAvdHallbarhetButtonActionPerformed
        // TODO add your handling code here:
                String status = "Planerat";
        
        if(Validering.kollaStatus(status)){
            try{
                String sql = "SELECT DISTINCT p.projektnamn FROM projekt p " +
                        "JOIN proj_hallbarhet ph ON p.pid = ph.pid " +
                        "JOIN avd_hallbarhet ah ON ph.hid = ah.hid " +
                        "JOIN avdelning a ON ah.avdid = a.avdid " +
                        "WHERE a.namn = 'Avdelning för Hållbar Energi och Klimatförändringar' "+
                        "AND p.status = '" + status + "'";
                
               var resultat = idb.fetchRows(sql);
               StringBuilder sb = new StringBuilder();
               
               if(resultat != null && !resultat.isEmpty()){
                   for(var rad : resultat){
                       sb.append(rad.get("projektnamn")).append("\n");
                   }
                   hallbarhetAvdProjektField.setText(sb.toString());
               }else{
                   hallbarhetAvdProjektField.setText("Inga projekt med status '" + status + "' hittades.");
               }
            }catch (Exception e){
                hallbarhetAvdProjektField.setText("Fel: " + e.getMessage());
            }
        }else {
            hallbarhetAvdProjektField.setText("Ogiltig status: " + status);
        }
    }//GEN-LAST:event_plaAvdHallbarhetButtonActionPerformed

    private void sokHandlaggareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokHandlaggareButtonActionPerformed
        // TODO add your handling code here:
     String sokterm = sokHandlaggarField.getText().trim();

    if (sokterm.isEmpty()) {
        hallbarhetPersonalField.setText("Ange namn eller e-post att söka efter.");
        return;
    }

    try {  
        String avdidSql = "SELECT avdelning FROM anstalld WHERE aid = " + aid;
        String avdid = idb.fetchSingle(avdidSql);

                     String sql = "SELECT a.fornamn, a.efternamn, a.epost, a.telefon, a.adress " +
                     "FROM anstalld a " +
                     "JOIN handlaggare h ON a.aid = h.aid " +
                     "JOIN avdelning av ON a.avdelning = av.avdid " +
                     "WHERE av.namn = 'Avdelning för Hållbar Energi och Klimatförändringar' " +
                     "AND (a.fornamn LIKE '%" + sokterm + "%' " +
                     "OR a.efternamn LIKE '%" + sokterm + "%' " +
                     "OR a.epost LIKE '%" + sokterm + "%')";

        var resultat = idb.fetchRows(sql);

        if (resultat != null && !resultat.isEmpty()) {
            StringBuilder sb = new StringBuilder();
            for (var rad : resultat) {
                sb.append("Namn: ").append(rad.get("fornamn")).append(" ").append(rad.get("efternamn")).append("\n")
                  .append("E-post: ").append(rad.get("epost")).append("\n")
                  .append("Telefon: ").append(rad.get("telefon")).append("\n")
                  .append("Adress: ").append(rad.get("adress")).append("\n")
                  .append("--------------------------\n");
            }
            hallbarhetPersonalField.setText(sb.toString());
        } else {
            hallbarhetPersonalField.setText("Ingen handläggare hittades med termen: " + sokterm);
        }

    } catch (Exception e) {
        hallbarhetPersonalField.setText("Fel vid sökning: " + e.getMessage());
    }
    }//GEN-LAST:event_sokHandlaggareButtonActionPerformed

    private void sokProjektDatumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokProjektDatumButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sokProjektDatumButtonActionPerformed

    private void sokHandlaggarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokHandlaggarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sokHandlaggarFieldActionPerformed

    private void sokProjektFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokProjektFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sokProjektFieldActionPerformed

    private void sokProjektField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokProjektField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sokProjektField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHallbarhetavd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHallbarhetavd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHallbarhetavd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHallbarhetavd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Hallbarhetavd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HallbarhetavdTillbakaButton;
    private javax.swing.JToggleButton aAvdHallbarhetButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hallbarhetAvdPersonalButton;
    private javax.swing.JButton hallbarhetAvdProjektButton;
    private javax.swing.JTextArea hallbarhetAvdProjektField;
    private javax.swing.JTextArea hallbarhetPersonalField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton pAvdHallbarhetButton;
    private javax.swing.JToggleButton plaAvdHallbarhetButton;
    private javax.swing.JTextField sokHandlaggarField;
    private javax.swing.JButton sokHandlaggareButton;
    private javax.swing.JButton sokProjektDatumButton;
    private javax.swing.JTextField sokProjektField;
    private javax.swing.JTextField sokProjektField2;
    private javax.swing.JLabel sokProjektLabel;
    private javax.swing.JLabel sokProjektLabel2;
    // End of variables declaration//GEN-END:variables
}
