package inlämningsprojekt_ny;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import oru.inf.InfDB;
/** 
 *
 * @author joelj
 */
public class AdminAvdelning extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;
    private int aid;

    /**
     * Creates new form Avdelning
     */
    public AdminAvdelning(InfDB idb, String inloggadAnvandare, int aid) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.aid = aid;
        initComponents();

 


}
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avdButton1 = new javax.swing.JButton();
        avdbutton2 = new javax.swing.JButton();
        avdButton3 = new javax.swing.JButton();
        avdTillbakaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        avdButton1.setText("Hållbar energi");
        avdButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avdButton1ActionPerformed(evt);
            }
        });

        avdbutton2.setText("Samhällsutveckling");
        avdbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avdbutton2ActionPerformed(evt);
            }
        });

        avdButton3.setText("Teknologisk innovation");
        avdButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avdButton3ActionPerformed(evt);
            }
        });

        avdTillbakaButton.setText("Tillbaka");
        avdTillbakaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avdTillbakaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(avdButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(avdbutton2)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(avdButton1)
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(avdTillbakaButton)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avdTillbakaButton)
                .addGap(33, 33, 33)
                .addComponent(avdButton1)
                .addGap(32, 32, 32)
                .addComponent(avdbutton2)
                .addGap(32, 32, 32)
                .addComponent(avdButton3)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avdButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avdButton1ActionPerformed
      new Hallbarhetavd(idb, inloggadAnvandare,aid).setVisible(true);
      this.dispose();
      
    }//GEN-LAST:event_avdButton1ActionPerformed

    private void avdTillbakaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avdTillbakaButtonActionPerformed
        // TODO add your handling code here:
        new AdminMeny(idb, inloggadAnvandare, aid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_avdTillbakaButtonActionPerformed

    private void avdbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avdbutton2ActionPerformed
        // TODO add your handling code here:
        new SamhallutvecklingAvd(idb, inloggadAnvandare, aid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_avdbutton2ActionPerformed

    private void avdButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avdButton3ActionPerformed
        // TODO add your handling code here:
        new TeknologiskInnovationavd(idb, inloggadAnvandare, aid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_avdButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Avdelning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avdButton1;
    private javax.swing.JButton avdButton3;
    private javax.swing.JButton avdTillbakaButton;
    private javax.swing.JButton avdbutton2;
    // End of variables declaration//GEN-END:variables
 }
