package inlämningsprojekt_ny;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import oru.inf.InfDB;
/**
 *
 * @author paulu
 */
public class AdminTeknologiskInnovationavd extends javax.swing.JFrame {

    private InfDB idb;
    private String InloggadAnvandare;
    private int aid;
    /**
     * Creates new form TeknologiskInnovationavd
     */
    public AdminTeknologiskInnovationavd(InfDB idb, String InloggadAnvandare, int aid) {
        this.idb = idb;
        this.InloggadAnvandare = InloggadAnvandare;
        this.aid = aid;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        TekAvdTillbakaButton = new javax.swing.JButton();
        TekAvdPersonalButton = new javax.swing.JButton();
        TekAvdProjektButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TekAvdProjektField = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TekAvdPersonalField = new javax.swing.JTextArea();
        plaAvdTekInnovationButton = new javax.swing.JToggleButton();
        pAvdTekInnovationButton = new javax.swing.JToggleButton();
        aAvdTekInnovationButton = new javax.swing.JToggleButton();
        sokHandlaggarTekField = new javax.swing.JTextField();
        sokHandlaggareTekButton = new javax.swing.JButton();
        sokProjektTekLabel = new javax.swing.JLabel();
        sokProjektTekLabel2 = new javax.swing.JLabel();
        sokProjektTekField = new javax.swing.JTextField();
        sokProjektTekField2 = new javax.swing.JTextField();
        sokProjektDatumTekButton = new javax.swing.JButton();
        andraNamnTekField = new javax.swing.JTextField();
        raderaTekButton = new javax.swing.JButton();
        laggTillTekButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TekAvdTillbakaButton.setText("Tillbaka");
        TekAvdTillbakaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TekAvdTillbakaButtonActionPerformed(evt);
            }
        });

        TekAvdPersonalButton.setText("Personal Lista");
        TekAvdPersonalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TekAvdPersonalButtonActionPerformed(evt);
            }
        });

        TekAvdProjektButton.setText("Projekt Lista");
        TekAvdProjektButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TekAvdProjektButtonActionPerformed(evt);
            }
        });

        TekAvdProjektField.setColumns(20);
        TekAvdProjektField.setRows(5);
        jScrollPane2.setViewportView(TekAvdProjektField);

        TekAvdPersonalField.setColumns(20);
        TekAvdPersonalField.setRows(5);
        jScrollPane3.setViewportView(TekAvdPersonalField);

        buttonGroup2.add(plaAvdTekInnovationButton);
        plaAvdTekInnovationButton.setText("Planerat");
        plaAvdTekInnovationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plaAvdTekInnovationButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(pAvdTekInnovationButton);
        pAvdTekInnovationButton.setText("Pågående");
        pAvdTekInnovationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAvdTekInnovationButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(aAvdTekInnovationButton);
        aAvdTekInnovationButton.setText("Avslutat");
        aAvdTekInnovationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAvdTekInnovationButtonActionPerformed(evt);
            }
        });

        sokHandlaggarTekField.setColumns(12);
        sokHandlaggarTekField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokHandlaggarTekFieldActionPerformed(evt);
            }
        });

        sokHandlaggareTekButton.setText("Sök Handläggare");
        sokHandlaggareTekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokHandlaggareTekButtonActionPerformed(evt);
            }
        });

        sokProjektTekLabel.setText("Från:");

        sokProjektTekLabel2.setText("Till:");

        sokProjektTekField.setColumns(5);
        sokProjektTekField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokProjektTekFieldActionPerformed(evt);
            }
        });

        sokProjektTekField2.setColumns(5);
        sokProjektTekField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokProjektTekField2ActionPerformed(evt);
            }
        });

        sokProjektDatumTekButton.setText("Sök Projekt");
        sokProjektDatumTekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokProjektDatumTekButtonActionPerformed(evt);
            }
        });

        andraNamnTekField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraNamnTekFieldActionPerformed(evt);
            }
        });

        raderaTekButton.setText("Radera");
        raderaTekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raderaTekButtonActionPerformed(evt);
            }
        });

        laggTillTekButton.setText("Lägg till");
        laggTillTekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laggTillTekButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TekAvdTillbakaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(plaAvdTekInnovationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pAvdTekInnovationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aAvdTekInnovationButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sokHandlaggarTekField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(TekAvdPersonalButton)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TekAvdProjektButton)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sokHandlaggareTekButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(sokProjektTekLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sokProjektTekField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(sokProjektTekLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sokProjektTekField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(sokProjektDatumTekButton)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(andraNamnTekField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(raderaTekButton)
                                            .addComponent(laggTillTekButton))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TekAvdTillbakaButton)
                    .addComponent(plaAvdTekInnovationButton)
                    .addComponent(pAvdTekInnovationButton)
                    .addComponent(aAvdTekInnovationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sokProjektTekLabel)
                            .addComponent(sokProjektTekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sokProjektTekLabel2)
                            .addComponent(sokProjektTekField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sokProjektDatumTekButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sokHandlaggarTekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sokHandlaggareTekButton))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TekAvdPersonalButton)
                    .addComponent(TekAvdProjektButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(andraNamnTekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(raderaTekButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laggTillTekButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TekAvdTillbakaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TekAvdTillbakaButtonActionPerformed
        // TODO add your handling code here:
        new AdminAvdelning(idb, InloggadAnvandare, aid).setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_TekAvdTillbakaButtonActionPerformed

    private void TekAvdPersonalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TekAvdPersonalButtonActionPerformed
        // TODO add your handling code here:
                        try {
    String sql = "SELECT fornamn, efternamn FROM anstalld " + 
                 "JOIN avdelning ON anstalld.avdelning = avdelning.avdid " + 
                 "WHERE avdelning.namn = 'Avdelning för Teknologisk Innovation och Entreprenörskap'";

    var resultat = idb.fetchRows(sql);

    if (resultat != null && !resultat.isEmpty()) {
        StringBuilder sb = new StringBuilder();
        for (var rad : resultat) {
            sb.append(rad.get("fornamn")).append(" ").append(rad.get("efternamn")).append("\n");
        }
        TekAvdPersonalField.setText(sb.toString());
 
    } else {
        TekAvdPersonalField.setText("Inga personer hittades.");
  
    }
} catch (Exception e) {
    TekAvdPersonalField.setText("Fel: " + e.getMessage());

}
    }//GEN-LAST:event_TekAvdPersonalButtonActionPerformed

    private void TekAvdProjektButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TekAvdProjektButtonActionPerformed
        // TODO add your handling code here:
               try {
            String sql = "SELECT DISTINCT p.projektnamn FROM projekt p " + 
                    "JOIN proj_hallbarhet ph ON p.pid = ph.pid " + 
                    "JOIN avd_hallbarhet ah ON ph.hid = ah.hid " + 
                    "JOIN avdelning a ON ah.avdid = a.avdid " +
                    "WHERE a.namn = 'Avdelning för Teknologisk Innovation och Entreprenörskap'";
            
            var resultat = idb.fetchRows(sql);
            
            if (resultat != null && !resultat.isEmpty()) {
                StringBuilder sb = new StringBuilder();
                for (var rad : resultat) {
                    sb.append(rad.get("projektnamn")).append("\n");
                }
                TekAvdProjektField.setText(sb.toString());
                jScrollPane2.setVisible(true);
            } else {
                TekAvdProjektField.setText("Inga projekt hittades.");
                jScrollPane2.setVisible(true);
            }
      } catch (Exception e) {
          TekAvdProjektField.setText("Fel: " + e.getMessage());
          jScrollPane2.setVisible(true);
      }
    }//GEN-LAST:event_TekAvdProjektButtonActionPerformed

    private void plaAvdTekInnovationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plaAvdTekInnovationButtonActionPerformed
        // TODO add your handling code here:
                        String status = "Planerat";
        
        if(Validering.kollaStatus(status)){
            try{
                String sql = "SELECT DISTINCT p.projektnamn FROM projekt p " +
                        "JOIN proj_hallbarhet ph ON p.pid = ph.pid " +
                        "JOIN avd_hallbarhet ah ON ph.hid = ah.hid " +
                        "JOIN avdelning a ON ah.avdid = a.avdid " +
                        "WHERE a.namn = 'Avdelning för Teknologisk Innovation och Entreprenörskap' "+
                        "AND p.status = '" + status + "'";
                
               var resultat = idb.fetchRows(sql);
               StringBuilder sb = new StringBuilder();
               
               if(resultat != null && !resultat.isEmpty()){
                   for(var rad : resultat){
                       sb.append(rad.get("projektnamn")).append("\n");
                   }
                   TekAvdProjektField.setText(sb.toString());
               }else{
                   TekAvdProjektField.setText("Inga projekt med status '" + status + "' hittades.");
               }
            }catch (Exception e){
                TekAvdProjektField.setText("Fel: " + e.getMessage());
            }
        }else {
            TekAvdProjektField.setText("Ogiltig status: " + status);
        }   
    }//GEN-LAST:event_plaAvdTekInnovationButtonActionPerformed

    private void pAvdTekInnovationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAvdTekInnovationButtonActionPerformed
        // TODO add your handling code here:
                                String status = "Pågående";
        
        if(Validering.kollaStatus(status)){
            try{
                String sql = "SELECT DISTINCT p.projektnamn FROM projekt p " +
                        "JOIN proj_hallbarhet ph ON p.pid = ph.pid " +
                        "JOIN avd_hallbarhet ah ON ph.hid = ah.hid " +
                        "JOIN avdelning a ON ah.avdid = a.avdid " +
                        "WHERE a.namn = 'Avdelning för Teknologisk Innovation och Entreprenörskap' "+
                        "AND p.status = '" + status + "'";
                
               var resultat = idb.fetchRows(sql);
               StringBuilder sb = new StringBuilder();
               
               if(resultat != null && !resultat.isEmpty()){
                   for(var rad : resultat){
                       sb.append(rad.get("projektnamn")).append("\n");
                   }
                   TekAvdProjektField.setText(sb.toString());
               }else{
                   TekAvdProjektField.setText("Inga projekt med status '" + status + "' hittades.");
               }
            }catch (Exception e){
                TekAvdProjektField.setText("Fel: " + e.getMessage());
            }
        }else {
            TekAvdProjektField.setText("Ogiltig status: " + status);
        }   
    }//GEN-LAST:event_pAvdTekInnovationButtonActionPerformed

    private void aAvdTekInnovationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAvdTekInnovationButtonActionPerformed
        // TODO add your handling code here:
                                String status = "Avslutat";
        
        if(Validering.kollaStatus(status)){
            try{
                String sql = "SELECT DISTINCT p.projektnamn FROM projekt p " +
                        "JOIN proj_hallbarhet ph ON p.pid = ph.pid " +
                        "JOIN avd_hallbarhet ah ON ph.hid = ah.hid " +
                        "JOIN avdelning a ON ah.avdid = a.avdid " +
                        "WHERE a.namn = 'Avdelning för Teknologisk Innovation och Entreprenörskap' "+
                        "AND p.status = '" + status + "'";
                
               var resultat = idb.fetchRows(sql);
               StringBuilder sb = new StringBuilder();
               
               if(resultat != null && !resultat.isEmpty()){
                   for(var rad : resultat){
                       sb.append(rad.get("projektnamn")).append("\n");
                   }
                   TekAvdProjektField.setText(sb.toString());
               }else{
                   TekAvdProjektField.setText("Inga projekt med status '" + status + "' hittades.");
               }
            }catch (Exception e){
                TekAvdProjektField.setText("Fel: " + e.getMessage());
            }
        }else {
            TekAvdProjektField.setText("Ogiltig status: " + status);
        }   
    }//GEN-LAST:event_aAvdTekInnovationButtonActionPerformed

    private void sokHandlaggarTekFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokHandlaggarTekFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sokHandlaggarTekFieldActionPerformed

    private void sokHandlaggareTekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokHandlaggareTekButtonActionPerformed
        // TODO add your handling code here:
        String sokterm = sokHandlaggarTekField.getText().trim();

    if (sokterm.isEmpty()) {
        TekAvdPersonalField.setText("Ange namn eller e-post att söka efter.");
        return;
    }

    try {
        
        String avdidSql = "SELECT avdelning FROM anstalld WHERE aid = " + aid;
        String avdid = idb.fetchSingle(avdidSql);

       
       String sql = "SELECT a.fornamn, a.efternamn, a.epost, a.telefon, a.adress " +
                     "FROM anstalld a " +
                     "JOIN handlaggare h ON a.aid = h.aid " +
                     "JOIN avdelning av ON a.avdelning = av.avdid " +
                     "WHERE av.namn = 'Avdelning för Teknologisk Innovation och Entreprenörskap' " +
                     "AND (a.fornamn LIKE '%" + sokterm + "%' " +
                     "OR a.efternamn LIKE '%" + sokterm + "%' " +
                     "OR a.epost LIKE '%" + sokterm + "%')";

        var resultat = idb.fetchRows(sql);

        if (resultat != null && !resultat.isEmpty()) {
            StringBuilder sb = new StringBuilder();
            for (var rad : resultat) {
                sb.append("Namn: ").append(rad.get("fornamn")).append(" ").append(rad.get("efternamn")).append("\n")
                  .append("E-post: ").append(rad.get("epost")).append("\n")
                  .append("Telefon: ").append(rad.get("telefon")).append("\n")
                  .append("Adress: ").append(rad.get("adress")).append("\n")
                  .append("--------------------------\n");
                
            }
            TekAvdPersonalField.setText(sb.toString());
        } else {
            TekAvdPersonalField.setText("Ingen handläggare hittades med termen: " + sokterm);
        }

    } catch (Exception e) {
        TekAvdPersonalField.setText("Fel vid sökning: " + e.getMessage());
    }                                                               
    }//GEN-LAST:event_sokHandlaggareTekButtonActionPerformed

    private void sokProjektTekFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokProjektTekFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sokProjektTekFieldActionPerformed

    private void sokProjektDatumTekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokProjektDatumTekButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sokProjektDatumTekButtonActionPerformed

    private void sokProjektTekField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokProjektTekField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sokProjektTekField2ActionPerformed

    private void andraNamnTekFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraNamnTekFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_andraNamnTekFieldActionPerformed

    private void raderaTekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raderaTekButtonActionPerformed
        // TODO add your handling code here:
                String namn = andraNamnTekField.getText().trim();
        
        if(namn.isEmpty() || !namn.contains(" ")){
            JOptionPane.showMessageDialog(null, "Skriv för- och efternamn.");
            return;
        }
        
        String fornamn = namn.substring(0, namn.indexOf(" "));
        String efternamn = namn.substring(namn.indexOf(" ") + 1);
        
        try{
            String sqlAid = "SELECT aid FROM anstalld WHERE fornamn = '" + fornamn.replace("'", "''") + "' AND efternamn = '" + efternamn.replace("'", "''") + "'";
            String aid = idb.fetchSingle(sqlAid);
            
            if(aid == null){
                JOptionPane.showMessageDialog(null, "Personen finns inte:" + namn);
                return;
            }
            
            String deleteAnsProj = "DELETE FROM ans_proj WHERE aid = " + aid;
            idb.delete(deleteAnsProj);
            
            String deletePerson = "DELETE FROM ans_proj WHERE aid = " + aid;
            idb.delete(deletePerson);
            
            JOptionPane.showMessageDialog(null, "Personen raderades: " + namn);
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Fel vid radering: " + e.getMessage());
        }
    }//GEN-LAST:event_raderaTekButtonActionPerformed

    private void laggTillTekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laggTillTekButtonActionPerformed
        // TODO add your handling code here:
                String namn = andraNamnTekField.getText().trim();
        
        if(namn.isEmpty() || !namn.contains(" ")){
            JOptionPane.showMessageDialog(null, "Skriv för- och efternamn.");
            return;
        }
        
        String fornamn = namn.substring(0, namn.indexOf(" "));
        String efternamn = namn.substring(namn.indexOf(" ") + 1);
        
        try{
            java.util.Random rand = new java.util.Random();
            int aid;
            
            String losenord = generateRandomPassword(11);
            
            for(int i = 0; i < 10; i++){
            aid = rand.nextInt(100000);
            String checkSql = "SELECT aid FROM anstalld WHERE aid = " + aid;
            if(idb.fetchSingle(checkSql) == null){
            String sql = "INSERT INTO anstalld (aid, fornamn, efternamn, epost, telefon, adress, avdelning, losenord, anstallningsdatum) VALUES (" +
                   aid + ", " +
                   "'" + fornamn.replace("'", "''") + "', " +
                   "'" + efternamn.replace("'", "''") + "', " +
                   "'default@example.com', '-', '-', 1, '" + losenord + "', '2024-01-01')";

            
            idb.insert(sql);
            JOptionPane.showMessageDialog(null, "Person tillagd: " + namn + "\nLösenord: " + losenord);
            return;
            }
          }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fel vid tillägg: " + e.getMessage());
        }
    }//GEN-LAST:event_laggTillTekButtonActionPerformed

    private String generateRandomPassword(int lenght){
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder password = new StringBuilder();
        java.util.Random rnd = new java.util.Random();
        for (int i = 0; i < lenght; i++){
        password.append(chars.charAt(rnd.nextInt(chars.length())));                  // NY KOD
        }
        return password.toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTeknologiskInnovationavd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTeknologiskInnovationavd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTeknologiskInnovationavd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTeknologiskInnovationavd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TeknologiskInnovationavd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TekAvdPersonalButton;
    private javax.swing.JTextArea TekAvdPersonalField;
    private javax.swing.JButton TekAvdProjektButton;
    private javax.swing.JTextArea TekAvdProjektField;
    private javax.swing.JButton TekAvdTillbakaButton;
    private javax.swing.JToggleButton aAvdTekInnovationButton;
    private javax.swing.JTextField andraNamnTekField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton laggTillTekButton;
    private javax.swing.JToggleButton pAvdTekInnovationButton;
    private javax.swing.JToggleButton plaAvdTekInnovationButton;
    private javax.swing.JButton raderaTekButton;
    private javax.swing.JTextField sokHandlaggarTekField;
    private javax.swing.JButton sokHandlaggareTekButton;
    private javax.swing.JButton sokProjektDatumTekButton;
    private javax.swing.JTextField sokProjektTekField;
    private javax.swing.JTextField sokProjektTekField2;
    private javax.swing.JLabel sokProjektTekLabel;
    private javax.swing.JLabel sokProjektTekLabel2;
    // End of variables declaration//GEN-END:variables
}
