/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inlämningsprojekt_ny;

import oru.inf.InfDB;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.Map;

/**
 *
 * @author joelj
 */
public class AdminÄndraUppgifter extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;
    private int aid;

    /**
     * Creates new form AdminÄndraUppgifter
     */
    public AdminÄndraUppgifter(InfDB idb, String inloggadAnvandare, int aid) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.aid = aid;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminUppgifterTillbakaButton = new javax.swing.JButton();
        AndraUppgifterComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableInfoUppgifter = new javax.swing.JTable();
        laggTillButton = new javax.swing.JButton();
        SparaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminUppgifterTillbakaButton.setText("Tillbaka");
        AdminUppgifterTillbakaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminUppgifterTillbakaButtonActionPerformed(evt);
            }
        });

        AndraUppgifterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avdelning", "Projekt", "Land", "Partner" }));
        AndraUppgifterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraUppgifterComboBoxActionPerformed(evt);
            }
        });

        TableInfoUppgifter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableInfoUppgifter);

        laggTillButton.setText("Lägg till");
        laggTillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laggTillButtonActionPerformed(evt);
            }
        });

        SparaButton.setText("Spara ändring");
        SparaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SparaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AdminUppgifterTillbakaButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AndraUppgifterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(laggTillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(SparaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminUppgifterTillbakaButton)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AndraUppgifterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laggTillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SparaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminUppgifterTillbakaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminUppgifterTillbakaButtonActionPerformed
        // TODO add your handling code here:
        new AdminMeny(idb, inloggadAnvandare, aid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminUppgifterTillbakaButtonActionPerformed

    private void AndraUppgifterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraUppgifterComboBoxActionPerformed
        // TODO add your handling code here:
        String selected = AndraUppgifterComboBox.getSelectedItem().toString();
        DefaultTableModel model = new DefaultTableModel();
        
        try {
            switch (selected) {
                case "Avdelning":
                    model.setColumnIdentifiers(new String[] { "ID", "Namn", "Adress", "Epost", "Telefon", "Stad", "Chef", "Beskrivning" });
                    var rows1 = idb.fetchRows("SELECT avdid, namn, adress, epost, telefon, stad, chef, beskrivning FROM avdelning");
                    for (var rad : rows1) {
                        model.addRow(new Object[] {
                            rad.get("avdid"),
                            rad.get("namn"),
                            rad.get("adress"),
                            rad.get("epost"),
                            rad.get("telefon"),
                            rad.get("stad"),
                            rad.get("chef"),
                            rad.get("beskrivning")
                        });
                    }
                    break;
            }
            
            TableInfoUppgifter.setModel(model);
            TableInfoUppgifter.getColumnModel().getColumn(0).setMinWidth(0);
            TableInfoUppgifter.getColumnModel().getColumn(0).setMaxWidth(0);
            TableInfoUppgifter.getColumnModel().getColumn(0).setWidth(0);
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Fel vid hämtning: " + e.getMessage());
        }
    }//GEN-LAST:event_AndraUppgifterComboBoxActionPerformed

    private void laggTillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laggTillButtonActionPerformed
        // TODO add your handling code here:
        try {
            String namn = JOptionPane.showInputDialog(this, "Ange avdelningens namn:");
            String adress = JOptionPane.showInputDialog(this, "Ange adress");
            String epost = JOptionPane.showInputDialog(this, "Ange Epost");
            String telefon = JOptionPane.showInputDialog(this, "Ange telefon");
            String stad = JOptionPane.showInputDialog(this, "Ange stad");
            String chef = JOptionPane.showInputDialog(this, "Ange chef");
            String beskrivning = JOptionPane.showInputDialog(this, "beskrivning");
            
            String sql = "INSERT INTO avdelning (namn, adress, epost, telefon, stad, chef, beskrivning) VALUES ('" 
                    + namn + "', '" + adress + "', '" + epost + "', '" + telefon + "', '" + stad + "', '" + chef + "', '" + beskrivning + "')";
            
            idb.insert(sql);
            JOptionPane.showMessageDialog(this, "Information tillagd!");
            
            AndraUppgifterComboBoxActionPerformed(null);
            
} catch (Exception e) {
        }
    }//GEN-LAST:event_laggTillButtonActionPerformed

    private void SparaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SparaButtonActionPerformed
        // TODO add your handling code here:
        if (TableInfoUppgifter.isEditing()); {
            TableInfoUppgifter.getCellEditor().stopCellEditing();
            
    }
        int rad = TableInfoUppgifter.getSelectedRow();
        
        if (rad == -1) {
            JOptionPane.showMessageDialog(this, "Välj en rad att spara.");
            return;
        
        }
        
        try {
            String id = TableInfoUppgifter.getValueAt(rad, 0).toString();
            String namn = TableInfoUppgifter.getValueAt(rad, 1).toString();
            String adress = TableInfoUppgifter.getValueAt(rad, 2).toString();
            String epost = TableInfoUppgifter.getValueAt(rad, 3).toString();
            String telefon = TableInfoUppgifter.getValueAt(rad, 4).toString();
            String stad = TableInfoUppgifter.getValueAt(rad, 5).toString();
            String chef = TableInfoUppgifter.getValueAt(rad, 6).toString();
            String beskrivning = TableInfoUppgifter.getValueAt(rad, 7).toString();
            
            namn = namn.replace("'", "''");
            adress = adress.replace("'", "''");
            epost = epost.replace("'", "''");
            telefon = telefon.replace("'", "''");
            stad = stad.replace("'", "''");
            chef = chef.replace("'", "''");
            beskrivning = beskrivning.replace("'", "''");
            
            String sql = "UPDATE avdelning SET namn='" + namn + "', adress='" + adress + "', epost='" + epost + "', telefon='" + telefon + 
                    "',stad='" + stad + "', chef='" + chef + "', beskrivning='" + beskrivning + "' WHERE avdid=" + id;
            idb.update(sql);
            JOptionPane.showMessageDialog(this, "Uppgifter sparade!");
            AndraUppgifterComboBoxActionPerformed(null);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fel vid Uppdatering: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_SparaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminÄndraUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminUppgifterTillbakaButton;
    private javax.swing.JComboBox<String> AndraUppgifterComboBox;
    private javax.swing.JButton SparaButton;
    private javax.swing.JTable TableInfoUppgifter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton laggTillButton;
    // End of variables declaration//GEN-END:variables
}
