package inlämningsprojekt_ny;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
/**
 *
 * @author svanteskold
 */
public class Inloggning extends javax.swing.JFrame {

    private InfDB idb;
    /**
     * Creates new form inloggning
     */
    public Inloggning(InfDB idb) {
        this.idb= idb;
        initComponents();
        felmeddelandeLabel.setVisible(false);

        
 }
    /**
     * 
     */
/*
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">     
    /*
    private void initComponents() {

        epostLabel = new javax.swing.JLabel();
        losenordLabel = new javax.swing.JLabel();
        epostField = new javax.swing.JTextField();
        logInKnapp = new javax.swing.JButton();
        losenordField = new javax.swing.JPasswordField();
        felmeddelandeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        epostLabel.setText("E-post:");

        losenordLabel.setText("Lösenord:");

        epostField.setColumns(5);

        logInKnapp.setText("Logga in");
        logInKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInKnappActionPerformed(evt);
            }
        });

        losenordField.setColumns(5);
        losenordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losenordFieldActionPerformed(evt);
            }
        });

        felmeddelandeLabel.setForeground(new java.awt.Color(255, 0, 51));
        felmeddelandeLabel.setText("Felaktig epost eller lösenord");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(epostLabel)
                            .addComponent(losenordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logInKnapp)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(epostField, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(losenordField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(felmeddelandeLabel)))
                .addGap(0, 139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epostLabel)
                    .addComponent(epostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(losenordLabel)
                    .addComponent(losenordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(felmeddelandeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logInKnapp)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                  
    
*/
    
         

    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        epostLabel = new javax.swing.JLabel();
        losenordLabel = new javax.swing.JLabel();
        epostField = new javax.swing.JTextField();
        losenordField = new javax.swing.JPasswordField();
        logInKnapp = new javax.swing.JButton();
        felmeddelandeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        epostLabel.setText("E-post:");

        losenordLabel.setText("Lösenord:");

        epostField.setColumns(5);
        epostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epostFieldActionPerformed(evt);
            }
        });

        losenordField.setColumns(5);

        logInKnapp.setText("Logga in");
        logInKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInKnappActionPerformed(evt);
            }
        });

        felmeddelandeLabel.setForeground(new java.awt.Color(255, 0, 0));
        felmeddelandeLabel.setText("Felaktig epost eller lösenord");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(losenordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(losenordField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(felmeddelandeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(epostLabel)
                                .addGap(18, 18, 18)
                                .addComponent(epostField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(logInKnapp)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epostLabel)
                    .addComponent(epostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(losenordLabel)
                    .addComponent(losenordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(felmeddelandeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logInKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void epostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epostFieldActionPerformed

    private void logInKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInKnappActionPerformed
    String epost=epostField.getText();
        String losen=losenordField.getText();
        
        if (!Validering.faltInteTomt(epost)) {
            felmeddelandeLabel.setText ("Eposten får inte vara tom");
            felmeddelandeLabel.setVisible(true);
            return;
        }
        
        if (!Validering.faltInteTomt(losen)) {
            felmeddelandeLabel.setText("Lösenord får inte vara tom");
            felmeddelandeLabel.setVisible(true);
            return;
        }
        
        if (!Validering.arMailKorrekt(epost)) {
            felmeddelandeLabel.setText("Eposten måste vara korrekt");
            felmeddelandeLabel.setVisible(true);
            return;
        }
        
        if (!Validering.losenordKrav(losen)) {
            felmeddelandeLabel.setText("Lösenordet uppfyller inte kraven");
            felmeddelandeLabel.setVisible(true);
            return;
        }
        
        if (!Validering.arAnvandarnamnOchLosenordKorrekt(epost, losen, idb)) {
            felmeddelandeLabel.setText("Fel epost eller lösenord");
            felmeddelandeLabel.setVisible(true);
            return;
        }
        
        
        try {
           String fragaAdmin = "SELECT anstalld.aid, epost, losenord, admin.behorighetsniva FROM anstalld "
                   + "JOIN admin ON anstalld.aid = admin.aid "
                   + "WHERE epost = '" + epost + "' AND losenord = '" + losen + "' AND (admin.behorighetsniva = 1 or admin.behorighetsniva = 2);";
           var databassvarAdmin = idb.fetchRow(fragaAdmin);
           felmeddelandeLabel.setVisible(false);
           
           if (databassvarAdmin != null && databassvarAdmin.get("aid") !=null) {
               int aid = Integer.parseInt(databassvarAdmin.get("aid"));
               new AdminMeny(idb, epost, aid).setVisible(true);
               this.dispose();
               return;
           }
           
           String fragaProjektchef = "SELECT anstalld.epost, anstalld.losenord, anstalld.aid FROM anstalld "
                   + "JOIN projekt ON anstalld.aid = projekt.projektchef WHERE anstalld.epost = '" + epost + "' AND anstalld.losenord = '" + losen + "';";
           
           var databassvarProjektchef = idb.fetchRow(fragaProjektchef);
           if (databassvarProjektchef != null && databassvarProjektchef.get("aid") !=null) {
               int aid = Integer.parseInt(databassvarProjektchef.get("aid"));
               new ProjektchefMeny(idb, epost, aid).setVisible(true);
               this.dispose();
               return;
           }
  
           
           String fragaHandlaggare = "SELECT epost, losenord, aid FROM anstalld WHERE epost = '" + epost + "' and losenord = '" + losen + "';";
           var databassvarHandlaggare = idb.fetchRow(fragaHandlaggare);
           
           if (databassvarHandlaggare !=null && databassvarHandlaggare.get("aid") != null) {
               int aid = Integer.parseInt(databassvarHandlaggare.get("aid"));
               new Meny(idb, epost, aid).setVisible(true);
               this.dispose();
               return;
           }
          
               felmeddelandeLabel.setText("Fel lösenord eller epost!");
           
        } catch (InfException e) {
            System.out.println(e.getMessage());
        }
                  
    }//GEN-LAST:event_logInKnappActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField epostField;
    private javax.swing.JLabel epostLabel;
    private javax.swing.JLabel felmeddelandeLabel;
    private javax.swing.JButton logInKnapp;
    private javax.swing.JPasswordField losenordField;
    private javax.swing.JLabel losenordLabel;
    // End of variables declaration//GEN-END:variables
    {
    
}}