package inlämningsprojekt_ny;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author svanteskold
 */
public class Meny extends javax.swing.JFrame {
private InfDB idb;
private String inloggadAnvandare;
    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb,String inloggadAnvandare) {
        this.idb=idb;
        this.inloggadAnvandare=inloggadAnvandare;
             initComponents();
             inloggadAnvandareLabel.setText(inloggadAnvandare);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inloggadAnvandareLabel = new javax.swing.JLabel();
        minaProjektButton = new javax.swing.JButton();
        avdelningButton = new javax.swing.JButton();
        hallbarhetsmalenButton = new javax.swing.JButton();
        minProfilButton = new javax.swing.JButton();
        huvudmenyLabel = new javax.swing.JLabel();
        loggaUtButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inloggadAnvandareLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        inloggadAnvandareLabel.setText("Användare:");

        minaProjektButton.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        minaProjektButton.setText("Mina Projekt");
        minaProjektButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minaProjektButtonActionPerformed(evt);
            }
        });

        avdelningButton.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        avdelningButton.setText("Avdelning");
        avdelningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avdelningButtonActionPerformed(evt);
            }
        });

        hallbarhetsmalenButton.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        hallbarhetsmalenButton.setText("Hållbarhetsmålen");
        hallbarhetsmalenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallbarhetsmalenButtonActionPerformed(evt);
            }
        });

        minProfilButton.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        minProfilButton.setText("Min Profil");
        minProfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minProfilButtonActionPerformed(evt);
            }
        });

        huvudmenyLabel.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        huvudmenyLabel.setText("Huvudmeny");

        loggaUtButton.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        loggaUtButton.setText("Logga Ut");
        loggaUtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggaUtButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(minProfilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 164, Short.MAX_VALUE)
                                .addComponent(minaProjektButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(avdelningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addComponent(hallbarhetsmalenButton)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inloggadAnvandareLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)
                                .addComponent(huvudmenyLabel))
                            .addComponent(loggaUtButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(huvudmenyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inloggadAnvandareLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minProfilButton)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hallbarhetsmalenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(avdelningButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minaProjektButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(loggaUtButton)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avdelningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avdelningButtonActionPerformed
    // TODO add your handling code here:
    new Avdelning(idb, inloggadAnvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_avdelningButtonActionPerformed

    private void loggaUtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggaUtButtonActionPerformed
        // TODO add your handling code here:
        new Inloggning(idb).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_loggaUtButtonActionPerformed

    private void minaProjektButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minaProjektButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minaProjektButtonActionPerformed

    private void hallbarhetsmalenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallbarhetsmalenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hallbarhetsmalenButtonActionPerformed

    private void minProfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minProfilButtonActionPerformed
        // TODO add your handling code here:
        String sqlFraga="SELECT aid FROM anstalld WHERE epost = '" + inloggadAnvandare+"';";
        String userId;
    try {
        userId = idb.fetchSingle(sqlFraga);
          int aid = Integer.parseInt(userId);
        new Personuppgifter(idb, aid).setVisible(true);
        this.dispose();
    } catch (InfException ex) {
        Logger.getLogger(Meny.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_minProfilButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Meny().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avdelningButton;
    private javax.swing.JButton hallbarhetsmalenButton;
    private javax.swing.JLabel huvudmenyLabel;
    private javax.swing.JLabel inloggadAnvandareLabel;
    private javax.swing.JButton loggaUtButton;
    private javax.swing.JButton minProfilButton;
    private javax.swing.JButton minaProjektButton;
    // End of variables declaration//GEN-END:variables
}
