package inlämningsprojekt_ny;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.HashMap;
import oru.inf.InfDB;
import javax.swing.JOptionPane;
import oru.inf.InfException;
/**
 *
 * @author paulu
 */
public class Personuppgifter extends javax.swing.JFrame {

    /**
     * Creates new form Personuppgifter
     */
    private InfDB idb;
    private int aid;
    private String inloggadAnvandare;
    
    public Personuppgifter(InfDB idb, int aid, String inloggadAnvandare) {
        this.idb = idb;
        this.aid = aid;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        visaPersonuppgifter();
    }

    private Personuppgifter() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void visaPersonuppgifter(){
        try{
            String sql  = "SELECT epost, telefon, adress, losenord FROM anstalld WHERE anstalld_id = "+aid;
            HashMap<String, String> data = idb.fetchRow(sql);
            
            if(data != null){
                epostField.setText(data.get("epost"));
                telefonField.setText(data.get("telefon"));
                adressField.setText(data.get("adress"));
                losenordField.setText(data.get("losenord"));
            }
        }catch(InfException e){
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av uppgifter: "+ e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        andralosenordLabel = new javax.swing.JLabel();
        andraepostLabel = new javax.swing.JLabel();
        andratelefonLabel = new javax.swing.JLabel();
        sparaButton = new javax.swing.JButton();
        andraadressLabel = new javax.swing.JLabel();
        losenordField = new javax.swing.JPasswordField();
        epostField = new javax.swing.JTextField();
        telefonField = new javax.swing.JTextField();
        adressField = new javax.swing.JTextField();
        persUppgifterTillbakaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        andralosenordLabel.setText("Ändra lösenord:");

        andraepostLabel.setText("Ändra E-post:");

        andratelefonLabel.setText("Ändra telefon:");

        sparaButton.setText("Spara");
        sparaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparaButtonActionPerformed(evt);
            }
        });

        andraadressLabel.setText("Ändra adress:");

        losenordField.setColumns(5);
        losenordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losenordFieldActionPerformed(evt);
            }
        });

        epostField.setColumns(5);
        epostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epostFieldActionPerformed(evt);
            }
        });

        telefonField.setColumns(5);

        adressField.setColumns(5);

        persUppgifterTillbakaButton.setText("Tillbaka");
        persUppgifterTillbakaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persUppgifterTillbakaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(andralosenordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(andraepostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(epostField)
                                    .addComponent(losenordField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(andratelefonLabel)
                                .addGap(18, 18, 18)
                                .addComponent(telefonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sparaButton)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(andraadressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(persUppgifterTillbakaButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(persUppgifterTillbakaButton)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(losenordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andralosenordLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andraepostLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(andraadressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(andratelefonLabel))
                        .addGap(18, 18, 18)
                        .addComponent(adressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(sparaButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sparaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparaButtonActionPerformed
        String epost = epostField.getText().trim();
        String telefon = telefonField.getText().trim();
        String adress = adressField.getText().trim();
        String losenord = new String(losenordField.getPassword()).trim();
        
        if(epost.isEmpty() || telefon.isEmpty() || adress.isEmpty() || losenord.isEmpty()){
            JOptionPane.showMessageDialog(this, "Alla fält måste vara ifyllda!");
            return;
        }
        try{
            String sql = "UPDATE  anstalld SET"
                    +"epost ='"+epost+"',"
                    +"telefon = '"+telefon+"',"
                    +"adress='"+adress+"',"
                    +"losenord='"+losenord+"'"
                    +"WHERE anstalld_id ="+aid;
            
            idb.update(sql);
            JOptionPane.showMessageDialog(this, "Uppgift har sparats!");
        }catch(InfException e){
            JOptionPane.showMessageDialog(this, "Fel vid uppdatering: "+e.getMessage());
        }
    }//GEN-LAST:event_sparaButtonActionPerformed

    private void losenordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_losenordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_losenordFieldActionPerformed

    private void epostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epostFieldActionPerformed

    private void persUppgifterTillbakaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persUppgifterTillbakaButtonActionPerformed
        // TODO add your handling code here:
        new Meny(idb, inloggadAnvandare, aid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_persUppgifterTillbakaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personuppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personuppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personuppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personuppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Personuppgifter().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adressField;
    private javax.swing.JLabel andraadressLabel;
    private javax.swing.JLabel andraepostLabel;
    private javax.swing.JLabel andralosenordLabel;
    private javax.swing.JLabel andratelefonLabel;
    private javax.swing.JTextField epostField;
    private javax.swing.JPasswordField losenordField;
    private javax.swing.JButton persUppgifterTillbakaButton;
    private javax.swing.JButton sparaButton;
    private javax.swing.JTextField telefonField;
    // End of variables declaration//GEN-END:variables
}
