/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inlämningsprojekt_ny;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author svanteskold
 */
public class ProjektchefStatistik extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    private int aid;
    /**
     * Creates new form ProjektchefStatistik
     */
    public ProjektchefStatistik(InfDB idb,String inloggadAnvandare, int aid) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.aid = aid;
        initComponents();
        hamtaProjektKostnad();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void hamtaProjektKostnad() {
    try {
        // SQL-fråga som hämtar projektnamn och kostnad för alla projekt som tillhör projektchefen
        String sql = "SELECT projektnamn, kostnad FROM projekt WHERE projektchef = " + aid;

        var resultatLista = idb.fetchRows(sql);

        if (resultatLista != null && !resultatLista.isEmpty()) {
            int totalKostnad = 0;
            StringBuilder text = new StringBuilder();
            text.append("Projekt och kostnader:\n");

            for (var rad : resultatLista) {
                String projektnamn = rad.get("projektnamn");
                String kostnadStr = rad.get("kostnad");
                double kostnad = Double.parseDouble(kostnadStr);
                totalKostnad += kostnad;
                text.append(projektnamn).append(": ").append(kostnad).append(" kr\n");
            }

            text.append("\nTotalkostnad för dina projekt: ").append(totalKostnad).append(" kr");

            statistikKostnadArea.setText(text.toString());

        } else {
            statistikKostnadArea.setText("Du har inga projekt eller inga kostnader registrerade.");
        }
    } catch (InfException e) {
        statistikKostnadArea.setText("Fel vid hämtning: " + e.getMessage());
    }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projektchefStatTillbakaButton = new javax.swing.JButton();
        rubrikKostnadLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statistikKostnadArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projektchefStatTillbakaButton.setText("Tillbaka");
        projektchefStatTillbakaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projektchefStatTillbakaButtonActionPerformed(evt);
            }
        });

        rubrikKostnadLabel.setBackground(new java.awt.Color(204, 204, 204));
        rubrikKostnadLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rubrikKostnadLabel.setText("Kostnad över mina projekt som projektchef");

        statistikKostnadArea.setColumns(20);
        statistikKostnadArea.setRows(5);
        jScrollPane1.setViewportView(statistikKostnadArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(projektchefStatTillbakaButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(rubrikKostnadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(projektchefStatTillbakaButton)
                .addGap(23, 23, 23)
                .addComponent(rubrikKostnadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projektchefStatTillbakaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projektchefStatTillbakaButtonActionPerformed
        // TODO add your handling code here:
        new ProjektchefMeny(idb, inloggadAnvandare, aid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_projektchefStatTillbakaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektchefStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektchefStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektchefStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektchefStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ProjektchefStatistik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton projektchefStatTillbakaButton;
    private javax.swing.JLabel rubrikKostnadLabel;
    private javax.swing.JTextArea statistikKostnadArea;
    // End of variables declaration//GEN-END:variables
}
